_l='backgroundColors'
_k='borderColors'
_j='tableCellProperties'
_i='tableProperties'
_h='styles'
_g='heading3'
_f='heading2'
_e='heading1'
_d='paragraph'
_c='mediaEmbed'
_b='italic'
_a='redis://localhost:6379'
_Z='MEDIA_ROOT'
_Y='STATIC_ROOT'
_X='manjarolinux-aspire4740'
_W='DB_NAME'
_V='ENGINE'
_U='BACKEND'
_T='localhost'
_S='ALLOWED_HOSTS'
_R='SECRET_KEY'
_Q='DB_PASSWORD'
_P='view'
_O='blockQuote'
_N='numberedList'
_M='bulletedList'
_L='heading'
_K='toolbar'
_J='class'
_I='title'
_H='model'
_G='true'
_F='NAME'
_E='default'
_D=True
_C='label'
_B='color'
_A='|'
import logging,os
from pathlib import Path
import socket
from encryption import OutboxEncryption
import socket
logger=logging.getLogger(__name__)
BASE_DIR=Path(__file__).resolve().parent.parent
lib=OutboxEncryption(BASE_DIR)
mplaint_key=[_Q,_R]
mplaint_list=[_S]
key=lib.dec_environ(mplaint_key,mplaint_list)
if not key:raise ValueError('No data found in environment, activate environment first!')
SECRET_KEY=key[_R]
DEBUG=key['DEBUG']
UNDER_CONSTRUCTION=key['UNDER_CONSTRUCTION']
UNDER_CONSTRUCTION_TEMPLATE='opd/construction.html'
LOGIN_REDIRECT_URL='/dashboard/dashboard'
LOGOUT_REDIRECT_URL='/'
ALLOWED_HOSTS=key[_S]
INSTALLED_APPS=['django.contrib.admin','django.contrib.auth','django.contrib.contenttypes','django.contrib.sessions','django.contrib.messages','django.contrib.staticfiles','django.contrib.sites','django.contrib.humanize','embed_video','simple_open_graph','django_social_share','easy_thumbnails','hitcount','outbox_hitcount','opd','account','django_underconstruction','import_export','django_ckeditor_5','corsheaders','debug_toolbar','cachalot','mobiledetect']
EMAIL_HOST=_T
EMAIL_PORT=1025
IMPORT_EXPORT_USE_TRANSACTIONS=_D
MIDDLEWARE=['django.middleware.security.SecurityMiddleware','django.contrib.sessions.middleware.SessionMiddleware','corsheaders.middleware.CorsMiddleware','django.middleware.common.CommonMiddleware','django.middleware.csrf.CsrfViewMiddleware','django.contrib.auth.middleware.AuthenticationMiddleware','django.contrib.messages.middleware.MessageMiddleware','django.middleware.clickjacking.XFrameOptionsMiddleware','mobiledetect.middleware.DetectMiddleware','debug_toolbar.middleware.DebugToolbarMiddleware','django_underconstruction.middleware.UnderConstructionMiddleware']
DEBUG_TOOLBAR_PANELS=['cachalot.panels.CachalotPanel','debug_toolbar.panels.history.HistoryPanel','debug_toolbar.panels.versions.VersionsPanel','debug_toolbar.panels.timer.TimerPanel','debug_toolbar.panels.settings.SettingsPanel','debug_toolbar.panels.headers.HeadersPanel','debug_toolbar.panels.request.RequestPanel','debug_toolbar.panels.sql.SQLPanel','debug_toolbar.panels.staticfiles.StaticFilesPanel','debug_toolbar.panels.templates.TemplatesPanel','debug_toolbar.panels.cache.CachePanel','debug_toolbar.panels.signals.SignalsPanel','debug_toolbar.panels.redirects.RedirectsPanel','debug_toolbar.panels.profiling.ProfilingPanel']
ROOT_URLCONF='django_opd.urls'
TEMPLATES=[{_U:'django.template.backends.django.DjangoTemplates','DIRS':[BASE_DIR/'templates/'],'APP_DIRS':_D,'OPTIONS':{'context_processors':['django.template.context_processors.debug','django.template.context_processors.request','django.contrib.auth.context_processors.auth','django.contrib.messages.context_processors.messages','opd.processor.my_context','opd.processor.my_comment_count']}}]
WSGI_APPLICATION='django_opd.wsgi.application'
db_engine=key['DB_ENGINE']
if'sqlite3'in db_engine:DATABASES={_E:{_V:db_engine,_F:key[_W]}}
else:DATABASES={_E:{_V:db_engine,_F:key[_W],'USER':key['DB_USER'],'PASSWORD':key[_Q],'HOST':key['DB_HOST'],'PORT':key['DB_PORT']}}
AUTH_PASSWORD_VALIDATORS=[{_F:'django.contrib.auth.password_validation.MinimumLengthValidator'},{_F:'django.contrib.auth.password_validation.NumericPasswordValidator'}]
LANGUAGE_CODE='id'
TIME_ZONE='Asia/Makassar'
USE_I18N=_D
USE_L10N=_D
USE_TZ=_D
if socket.gethostname()==_X:STATIC_URL='static/'
else:STATIC_URL='https://cdn.lombokbaratkab.go.id/static/'
STATIC_ROOT=key[_Y]if key.get(_Y)else os.path.join(BASE_DIR,'staticfiles')
STATICFILES_DIRS=[os.path.join(BASE_DIR,'static')]
if socket.gethostname()==_X:MEDIA_URL='media/'
else:MEDIA_URL='https://cdn.lombokbaratkab.go.id/media/'
MEDIA_ROOT=key[_Z]if key.get(_Z)else os.path.join(BASE_DIR,'media')
SITE_ID=1
DEFAULT_AUTO_FIELD='django.db.models.BigAutoField'
LOCALE_PATHS=BASE_DIR/'locale',
HITCOUNT_KEEP_HIT_IN_DATABASE={'days':60}
HITCOUNT_KEEP_HIT_ACTIVE={'hours':1}
INTERNAL_IPS=['127.0.0.1',_T,'adminopd.lombokbaratkab.go.id']
CACHES={_E:{_U:'django.core.cache.backends.locmem.LocMemCache','LOCATION':'unique-snowflake'}}
CACHES_TIMEOUT=24*60*60
CELERY_BROKER_URL=_a
CELERY_RESULT_BACKEND=_a
CELERY_ENABLE_UTC=False
CELERY_TIMEZONE=TIME_ZONE
customColorPalette=[{_B:'hsl(4, 90%, 58%)',_C:'Red'},{_B:'hsl(340, 82%, 52%)',_C:'Pink'},{_B:'hsl(291, 64%, 42%)',_C:'Purple'},{_B:'hsl(262, 52%, 47%)',_C:'Deep Purple'},{_B:'hsl(231, 48%, 48%)',_C:'Indigo'},{_B:'hsl(207, 90%, 54%)',_C:'Blue'}]
CKEDITOR_5_CONFIGS={_E:{_K:[_L,_A,'bold',_b,'link',_M,_N,_O,'imageUpload']},'extends':{'blockToolbar':[_d,_e,_f,_g,_A,_M,_N,_A,_O],_c:{'previewsInData':_G},_K:[_L,_A,'outdent','indent',_A,'alignment',_A,'bold',_b,'underline','strikethrough',_A,'link',_A,'code','subscript','superscript','highlight',_A,_M,_N,'todoList',_A,'codeBlock','sourceEditing','insertImage',_A,_O,_A,'fontFamily','fontSize','fontColor','fontBackgroundColor',_c,'removeFormat','insertTable'],'image':{_K:['imageTextAlternative',_A,'imageStyle:alignLeft','imageStyle:alignRight','imageStyle:alignCenter','imageStyle:side',_A],_h:['full','side','alignLeft','alignRight','alignCenter']},'table':{'contentToolbar':['tableColumn','tableRow','mergeTableCells',_i,_j],_i:{_k:customColorPalette,_l:customColorPalette},_j:{_k:customColorPalette,_l:customColorPalette}},_L:{'options':[{_H:_d,_I:'Paragraph',_J:'ck-heading_paragraph'},{_H:_e,_P:'h1',_I:'Heading 1',_J:'ck-heading_heading1'},{_H:_f,_P:'h2',_I:'Heading 2',_J:'ck-heading_heading2'},{_H:_g,_P:'h3',_I:'Heading 3',_J:'ck-heading_heading3'}]}},'list':{'properties':{_h:_G,'startIndex':_G,'reversed':_G}}}