_i='backgroundColors'
_h='borderColors'
_g='tableCellProperties'
_f='tableProperties'
_e='styles'
_d='heading3'
_c='heading2'
_b='heading1'
_a='paragraph'
_Z='mediaEmbed'
_Y='italic'
_X='MEDIA_ROOT'
_W='STATIC_ROOT'
_V='DB_NAME'
_U='ENGINE'
_T='BACKEND'
_S='ALLOWED_HOSTS'
_R='SECRET_KEY'
_Q='DB_PASSWORD'
_P='view'
_O='blockQuote'
_N='numberedList'
_M='bulletedList'
_L='heading'
_K='toolbar'
_J='class'
_I='title'
_H='model'
_G='true'
_F='NAME'
_E='default'
_D=True
_C='label'
_B='color'
_A='|'
import logging,os
from pathlib import Path
from encryption import OutboxEncryption
logger=logging.getLogger(__name__)
BASE_DIR=Path(__file__).resolve().parent.parent
lib=OutboxEncryption(BASE_DIR)
mplaint_key=[_Q,_R]
mplaint_list=[_S]
key=lib.dec_environ(mplaint_key,mplaint_list)
if not key:raise ValueError('No data found in environment, activate environment first!')
SECRET_KEY=key[_R]
DEBUG=key['DEBUG']
UNDER_CONSTRUCTION=key['UNDER_CONSTRUCTION']
UNDER_CONSTRUCTION_TEMPLATE='opd/construction.html'
LOGIN_REDIRECT_URL='/dashboard/dashboard'
LOGOUT_REDIRECT_URL='/'
ALLOWED_HOSTS=key[_S]
INSTALLED_APPS=['django.contrib.admin','django.contrib.auth','django.contrib.contenttypes','django.contrib.sessions','django.contrib.messages','django.contrib.staticfiles','django.contrib.sites','django.contrib.humanize','embed_video','simple_open_graph','django_social_share','hitcount','outbox_hitcount','opd','account','django_underconstruction','import_export','django_ckeditor_5','corsheaders','debug_toolbar','cachalot']
EMAIL_HOST='localhost'
EMAIL_PORT=1025
IMPORT_EXPORT_USE_TRANSACTIONS=_D
MIDDLEWARE=['django.middleware.security.SecurityMiddleware','django.contrib.sessions.middleware.SessionMiddleware','corsheaders.middleware.CorsMiddleware','django.middleware.common.CommonMiddleware','django.middleware.csrf.CsrfViewMiddleware','django.contrib.auth.middleware.AuthenticationMiddleware','django.contrib.messages.middleware.MessageMiddleware','django.middleware.clickjacking.XFrameOptionsMiddleware','debug_toolbar.middleware.DebugToolbarMiddleware','django_underconstruction.middleware.UnderConstructionMiddleware']
DEBUG_TOOLBAR_PANELS=['cachalot.panels.CachalotPanel','debug_toolbar.panels.history.HistoryPanel','debug_toolbar.panels.versions.VersionsPanel','debug_toolbar.panels.timer.TimerPanel','debug_toolbar.panels.settings.SettingsPanel','debug_toolbar.panels.headers.HeadersPanel','debug_toolbar.panels.request.RequestPanel','debug_toolbar.panels.sql.SQLPanel','debug_toolbar.panels.staticfiles.StaticFilesPanel','debug_toolbar.panels.templates.TemplatesPanel','debug_toolbar.panels.cache.CachePanel','debug_toolbar.panels.signals.SignalsPanel','debug_toolbar.panels.redirects.RedirectsPanel','debug_toolbar.panels.profiling.ProfilingPanel']
ROOT_URLCONF='django_opd.urls'
TEMPLATES=[{_T:'django.template.backends.django.DjangoTemplates','DIRS':[BASE_DIR/'templates/'],'APP_DIRS':_D,'OPTIONS':{'context_processors':['django.template.context_processors.debug','django.template.context_processors.request','django.contrib.auth.context_processors.auth','django.contrib.messages.context_processors.messages','opd.processor.my_context','opd.processor.my_comment_count']}}]
WSGI_APPLICATION='django_opd.wsgi.application'
db_engine=key['DB_ENGINE']
if'sqlite3'in db_engine:DATABASES={_E:{_U:db_engine,_F:key[_V]}}
else:DATABASES={_E:{_U:db_engine,_F:key[_V],'USER':key['DB_USER'],'PASSWORD':key[_Q],'HOST':key['DB_HOST'],'PORT':key['DB_PORT']}}
AUTH_PASSWORD_VALIDATORS=[{_F:'django.contrib.auth.password_validation.MinimumLengthValidator'},{_F:'django.contrib.auth.password_validation.NumericPasswordValidator'}]
LANGUAGE_CODE='id'
TIME_ZONE='Asia/Makassar'
USE_I18N=_D
USE_L10N=_D
USE_TZ=_D
STATIC_URL='/static/'
STATIC_ROOT=key[_W]if key.get(_W)else os.path.join(BASE_DIR,'staticfiles')
STATICFILES_DIRS=[os.path.join(BASE_DIR,'static')]
MEDIA_URL='/media/'
MEDIA_ROOT=key[_X]if key.get(_X)else os.path.join(BASE_DIR,'media')
SITE_ID=1
DEFAULT_AUTO_FIELD='django.db.models.BigAutoField'
LOCALE_PATHS=BASE_DIR/'locale',
HITCOUNT_KEEP_HIT_IN_DATABASE={'days':60}
HITCOUNT_KEEP_HIT_ACTIVE={'hours':1}
INTERNAL_IPS=['127.0.0.1']
CACHES={_E:{_T:'django.core.cache.backends.locmem.LocMemCache','LOCATION':'unique-snowflake'}}
CACHES_TIMEOUT=24*60*60
CELERY_ENABLE_UTC=False
CELERY_TIMEZONE=TIME_ZONE
customColorPalette=[{_B:'hsl(4, 90%, 58%)',_C:'Red'},{_B:'hsl(340, 82%, 52%)',_C:'Pink'},{_B:'hsl(291, 64%, 42%)',_C:'Purple'},{_B:'hsl(262, 52%, 47%)',_C:'Deep Purple'},{_B:'hsl(231, 48%, 48%)',_C:'Indigo'},{_B:'hsl(207, 90%, 54%)',_C:'Blue'}]
CKEDITOR_5_CONFIGS={_E:{_K:[_L,_A,'bold',_Y,'link',_M,_N,_O,'imageUpload']},'extends':{'blockToolbar':[_a,_b,_c,_d,_A,_M,_N,_A,_O],_Z:{'previewsInData':_G},_K:[_L,_A,'outdent','indent',_A,'alignment',_A,'bold',_Y,'underline','strikethrough',_A,'link',_A,'code','subscript','superscript','highlight',_A,_M,_N,'todoList',_A,'codeBlock','sourceEditing','insertImage',_A,_O,_A,'fontFamily','fontSize','fontColor','fontBackgroundColor',_Z,'removeFormat','insertTable'],'image':{_K:['imageTextAlternative',_A,'imageStyle:alignLeft','imageStyle:alignRight','imageStyle:alignCenter','imageStyle:side',_A],_e:['full','side','alignLeft','alignRight','alignCenter']},'table':{'contentToolbar':['tableColumn','tableRow','mergeTableCells',_f,_g],_f:{_h:customColorPalette,_i:customColorPalette},_g:{_h:customColorPalette,_i:customColorPalette}},_L:{'options':[{_H:_a,_I:'Paragraph',_J:'ck-heading_paragraph'},{_H:_b,_P:'h1',_I:'Heading 1',_J:'ck-heading_heading1'},{_H:_c,_P:'h2',_I:'Heading 2',_J:'ck-heading_heading2'},{_H:_d,_P:'h3',_I:'Heading 3',_J:'ck-heading_heading3'}]}},'list':{'properties':{_e:_G,'startIndex':_G,'reversed':_G}}}