_n='backgroundColors'
_m='borderColors'
_l='tableCellProperties'
_k='tableProperties'
_j='styles'
_i='heading3'
_h='heading2'
_g='heading1'
_f='paragraph'
_e='mediaEmbed'
_d='italic'
_c='redis://localhost:6379'
_b='MEDIA_ROOT'
_a='STATIC_ROOT'
_Z='DB_NAME'
_Y='ENGINE'
_X='BACKEND'
_W='localhost'
_V='ALLOWED_HOSTS'
_U='SECRET_KEY'
_T='DB_PASSWORD'
_S='view'
_R='code'
_Q='blockQuote'
_P='numberedList'
_O='bulletedList'
_N='heading'
_M='toolbar'
_L=False
_K='class'
_J='title'
_I='model'
_H='true'
_G='NAME'
_F='id'
_E='default'
_D=True
_C='label'
_B='color'
_A='|'
import logging,os,socket
from pathlib import Path
from encryption import OutboxEncryption
from django.utils.translation import gettext_lazy as _
logger=logging.getLogger(__name__)
DEBUG=_L
BASE_DIR=Path(__file__).resolve().parent.parent
lib=OutboxEncryption(BASE_DIR)
mplaint_key=[_T,_U]
mplaint_list=[_V]
key=lib.dec_environ(mplaint_key,mplaint_list)
if not key:raise ValueError('No data found in environment, activate environment first!')
SECRET_KEY=key[_U]
DEBUG=key['DEBUG']
UNDER_CONSTRUCTION=key['UNDER_CONSTRUCTION']
UNDER_CONSTRUCTION_TEMPLATE='opd/construction.html'
LOGIN_REDIRECT_URL='/dashboard/dashboard'
LOGOUT_REDIRECT_URL='/'
ALLOWED_HOSTS=key[_V]
INSTALLED_APPS=['django.contrib.admin','django.contrib.auth','django.contrib.contenttypes','django.contrib.sessions','django.contrib.messages','django.contrib.staticfiles','django.contrib.sites','django.contrib.humanize','embed_video','simple_open_graph','django_social_share','easy_thumbnails','hitcount','outbox_hitcount','opd','account','django_underconstruction','import_export','django_ckeditor_5','corsheaders','debug_toolbar','cachalot','mobiledetect','menu','parler']
EMAIL_HOST=_W
EMAIL_PORT=1025
IMPORT_EXPORT_USE_TRANSACTIONS=_D
MIDDLEWARE=['django.middleware.security.SecurityMiddleware','django.contrib.sessions.middleware.SessionMiddleware','django.middleware.common.CommonMiddleware','django.middleware.csrf.CsrfViewMiddleware','django.contrib.auth.middleware.AuthenticationMiddleware','django.contrib.messages.middleware.MessageMiddleware','django.middleware.clickjacking.XFrameOptionsMiddleware','mobiledetect.middleware.DetectMiddleware','debug_toolbar.middleware.DebugToolbarMiddleware','django_underconstruction.middleware.UnderConstructionMiddleware']
DEBUG_TOOLBAR_PANELS=['cachalot.panels.CachalotPanel','debug_toolbar.panels.history.HistoryPanel','debug_toolbar.panels.versions.VersionsPanel','debug_toolbar.panels.timer.TimerPanel','debug_toolbar.panels.settings.SettingsPanel','debug_toolbar.panels.headers.HeadersPanel','debug_toolbar.panels.request.RequestPanel','debug_toolbar.panels.sql.SQLPanel','debug_toolbar.panels.staticfiles.StaticFilesPanel','debug_toolbar.panels.templates.TemplatesPanel','debug_toolbar.panels.cache.CachePanel','debug_toolbar.panels.signals.SignalsPanel','debug_toolbar.panels.redirects.RedirectsPanel','debug_toolbar.panels.profiling.ProfilingPanel']
ROOT_URLCONF='django_opd.urls'
TEMPLATES=[{_X:'django.template.backends.django.DjangoTemplates','DIRS':[BASE_DIR/'templates/'],'APP_DIRS':_D,'OPTIONS':{'context_processors':['django.template.context_processors.debug','django.template.context_processors.request','django.contrib.auth.context_processors.auth','django.contrib.messages.context_processors.messages','opd.processor.my_context','opd.processor.my_comment_count']}}]
WSGI_APPLICATION='django_opd.wsgi.application'
db_engine=key['DB_ENGINE']
if'sqlite3'in db_engine:DATABASES={_E:{_Y:db_engine,_G:key[_Z]}}
else:DATABASES={_E:{_Y:db_engine,_G:key[_Z],'USER':key['DB_USER'],'PASSWORD':key[_T],'HOST':key['DB_HOST'],'PORT':key['DB_PORT']}}
AUTH_PASSWORD_VALIDATORS=[{_G:'django.contrib.auth.password_validation.MinimumLengthValidator'},{_G:'django.contrib.auth.password_validation.NumericPasswordValidator'}]
LANGUAGE_CODE=_F
TIME_ZONE='Asia/Makassar'
USE_I18N=_D
USE_L10N=_D
USE_TZ=_D
m_hostname='iwan-setiawan'
if socket.gethostname()==m_hostname:STATIC_URL='static/'
else:STATIC_URL='https://adminopd.lombokbaratkab.go.id/static/'
STATIC_ROOT=key[_a]if key.get(_a)else os.path.join(BASE_DIR,'staticfiles')
STATICFILES_DIRS=[os.path.join(BASE_DIR,'static')]
if socket.gethostname()==m_hostname:MEDIA_URL='media/'
else:MEDIA_URL='https://adminopd.lombokbaratkab.go.id/media/'
MEDIA_ROOT=key[_b]if key.get(_b)else os.path.join(BASE_DIR,'media')
SITE_ID=1
DEFAULT_AUTO_FIELD='django.db.models.BigAutoField'
HITCOUNT_KEEP_HIT_IN_DATABASE={'days':60}
HITCOUNT_KEEP_HIT_ACTIVE={'hours':1}
INTERNAL_IPS=['127.0.0.1',_W,'adminopd.lombokbaratkab.go.id']
CACHES={_E:{_X:'django.core.cache.backends.locmem.LocMemCache','LOCATION':'unique-snowflake'}}
CACHES_TIMEOUT=24*60*60
CELERY_BROKER_URL=_c
CELERY_RESULT_BACKEND=_c
CELERY_ENABLE_UTC=_L
CELERY_TIMEZONE=TIME_ZONE
customColorPalette=[{_B:'hsl(4, 90%, 58%)',_C:'Red'},{_B:'hsl(340, 82%, 52%)',_C:'Pink'},{_B:'hsl(291, 64%, 42%)',_C:'Purple'},{_B:'hsl(262, 52%, 47%)',_C:'Deep Purple'},{_B:'hsl(231, 48%, 48%)',_C:'Indigo'},{_B:'hsl(207, 90%, 54%)',_C:'Blue'}]
CKEDITOR_5_CONFIGS={_E:{_M:[_N,_A,'bold',_d,'link',_O,_P,_Q,'imageUpload']},'extends':{'blockToolbar':[_f,_g,_h,_i,_A,_O,_P,_A,_Q],_e:{'previewsInData':_H},_M:[_N,_A,'outdent','indent',_A,'alignment',_A,'bold',_d,'underline','strikethrough',_A,'link',_A,_R,'subscript','superscript','highlight',_A,_O,_P,'todoList',_A,'codeBlock','sourceEditing','insertImage',_A,_Q,_A,'fontFamily','fontSize','fontColor','fontBackgroundColor',_e,'removeFormat','insertTable'],'image':{_M:['imageTextAlternative',_A,'imageStyle:alignLeft','imageStyle:alignRight','imageStyle:alignCenter','imageStyle:side',_A],_j:['full','side','alignLeft','alignRight','alignCenter']},'table':{'contentToolbar':['tableColumn','tableRow','mergeTableCells',_k,_l],_k:{_m:customColorPalette,_n:customColorPalette},_l:{_m:customColorPalette,_n:customColorPalette}},_N:{'options':[{_I:_f,_J:'Paragraph',_K:'ck-heading_paragraph'},{_I:_g,_S:'h1',_J:'Heading 1',_K:'ck-heading_heading1'},{_I:_h,_S:'h2',_J:'Heading 2',_K:'ck-heading_heading2'},{_I:_i,_S:'h3',_J:'Heading 3',_K:'ck-heading_heading3'}]}},'list':{'properties':{_j:_H,'startIndex':_H,'reversed':_H}}}
LANGUAGES=(_F,_('Indonesia')),('en',_('English'))
LOCALE_PATHS=[os.path.join(BASE_DIR,'locale')]
PARLER_DEFAULT_LANGUAGE_CODE=_F
PARLER_LANGUAGES={1:({_R:_F},{_R:'en'}),_E:{'fallbacks':[_F],'hide_untranslated':_L}}