# Generated by Django 3.2.6 on 2022-02-18 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galery_video',
            name='embed_video',
        ),
    ]
