# Generated by Django 3.2.6 on 2022-02-18 11:52

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0002_remove_galery_video_embed_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='galery_video',
            name='embed_video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
