# Generated by Django 3.2.6 on 2022-02-18 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0003_galery_video_embed_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galery_video',
            name='embed_video',
        ),
    ]
