# Generated by Django 3.2.6 on 2022-06-09 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0005_galery_video_embed_video'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='berita',
            unique_together={('judul_seo', 'created_at')},
        ),
    ]
