# Generated by Django 3.2.6 on 2022-06-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0006_alter_berita_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='judul_seo',
            field=models.SlugField(blank=True, default='', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='berita',
            name='judul_seo',
            field=models.SlugField(blank=True, default='', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='galery_foto',
            name='judul_seo',
            field=models.SlugField(blank=True, default='', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='pengumuman',
            name='judul_seo',
            field=models.SlugField(blank=True, default='', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='popup',
            name='judul_seo',
            field=models.SlugField(blank=True, default='', max_length=500, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='berita',
            unique_together=set(),
        ),
    ]
