# Generated by Django 3.2.6 on 2022-06-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0009_info_hoax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_media',
            name='jenis',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('pinterest', 'Pinterest'), ('youtube', 'Youtube'), ('instagram', 'Instagram')], default='facebook', max_length=20),
        ),
    ]
