# Generated by Django 3.2.6 on 2022-06-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0010_alter_social_media_jenis'),
    ]

    operations = [
        migrations.AddField(
            model_name='galery_foto',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='galery_layanan',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link_terkait',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='social_media',
            name='link',
            field=models.URLField(),
        ),
    ]
