# Generated by Django 3.2.6 on 2022-07-25 09:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
        ('opd', '0011_auto_20220629_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instansi',
            name='admin',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='site',
            field=models.ManyToManyField(blank=True, to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='link_terkait',
            name='site',
            field=models.ManyToManyField(blank=True, to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='site',
            field=models.ManyToManyField(blank=True, to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='page_rss',
            name='site',
            field=models.ManyToManyField(blank=True, to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='page_widget',
            name='site',
            field=models.ManyToManyField(blank=True, to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='pejabat',
            name='site',
            field=models.ManyToManyField(blank=True, to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='site',
            field=models.ManyToManyField(blank=True, to='sites.Site'),
        ),
    ]
