# Generated by Django 3.2.6 on 2022-08-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0013_banner_all'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner_all',
            name='admin',
        ),
        migrations.AlterField(
            model_name='photo',
            name='jenis',
            field=models.CharField(blank=True, choices=[('logo-top', 'Logo Top'), ('logo-bottom', 'Logo Bottom'), ('banner-top', 'Banner Top'), ('banner-middle1', 'Banner Middle1'), ('banner-middle2', 'Banner Middle2'), ('banner-bottom', 'Banner Bottom'), ('highlight1', 'Highlight1'), ('highlight2', 'Highlight2'), ('highlight3', 'Highlight3'), ('bupati', 'Bupati'), ('wabup', 'Wabup'), ('sekda', 'Sekda'), ('pejabat-opd', 'Pejabat Opd'), ('popup', 'Popup'), ('banner-all', 'Banner All')], default='highlight1', max_length=20),
        ),
    ]
