# Generated by Django 3.2.6 on 2022-08-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0015_auto_20220831_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='word_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='berita',
            name='word_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pengumuman',
            name='word_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
