# Generated by Django 3.2.6 on 2023-03-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0016_auto_20220831_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='info_widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('categori', models.CharField(max_length=100)),
                ('publish_date', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('link', models.URLField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
