# Generated by Django 3.2.6 on 2023-07-06 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opd', '0018_auto_20230627_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galery_foto',
            name='deskripsi',
        ),
        migrations.RemoveField(
            model_name='galery_foto',
            name='link',
        ),
        migrations.AlterField(
            model_name='pejabat',
            name='admin',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
