# Generated by Django 3.2.6 on 2023-07-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0019_auto_20230707_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.CharField(choices=[('top', 'Top'), ('middle1', 'Middle1'), ('middle2', 'Middle2'), ('bottom', 'Bottom')], max_length=20),
        ),
    ]
