# Generated by Django 3.2.8 on 2023-12-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0020_alter_banner_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_hoax',
            name='link',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='info_hoax',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='info_hoax',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='info_widget',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
