# Generated by Django 3.2.8 on 2024-01-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0021_auto_20231230_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_widget',
            name='publish_date_convert',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
