# Generated by Django 3.2.8 on 2024-01-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0022_info_widget_publish_date_convert'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_hoax',
            name='publish_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='info_hoax',
            name='publish_date_convert',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
