# Generated by Django 3.2.8 on 2024-03-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0024_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kabkota', models.CharField(max_length=50, verbose_name='Kabupaten Kota')),
                ('kec', models.CharField(max_length=30, verbose_name='Kecamatan')),
                ('hari', models.CharField(max_length=20, verbose_name='Hari')),
                ('jam', models.CharField(max_length=20, verbose_name='Jam')),
                ('t', models.CharField(max_length=10, verbose_name='Temperatur')),
                ('hu', models.CharField(max_length=10, verbose_name='Kelembapan')),
                ('ws', models.CharField(max_length=10, verbose_name='Kecepatan Angin')),
                ('wd', models.CharField(max_length=10, verbose_name='Arah Angin')),
                ('weather_info', models.CharField(max_length=100, verbose_name='Info Cuaca')),
                ('img', models.CharField(max_length=255, verbose_name='Icon')),
                ('lat', models.CharField(max_length=50, verbose_name='Lat')),
                ('lon', models.CharField(max_length=50, verbose_name='Lon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
