# Generated by Django 3.2.8 on 2024-06-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0026_auto_20240326_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='jenis',
            field=models.CharField(blank=True, choices=[('logo-top', 'Logo Top'), ('logo-bottom', 'Logo Bottom'), ('banner-top', 'Banner Top'), ('banner-middle1', 'Banner Middle1'), ('banner-middle2', 'Banner Middle2'), ('banner-bottom', 'Banner Bottom'), ('highlight1', 'Highlight1'), ('highlight2', 'Highlight2'), ('highlight3', 'Highlight3'), ('highlight-editor', 'Highlight Editor'), ('bupati', 'Bupati'), ('wabup', 'Wabup'), ('sekda', 'Sekda'), ('pejabat-opd', 'Pejabat Opd'), ('popup', 'Popup'), ('banner-all', 'Banner All')], default='highlight1', max_length=20),
        ),
    ]
