# Generated by Django 3.2.8 on 2024-08-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0027_alter_photo_jenis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file_path',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
    ]
