# Generated by Django 3.2.8 on 2024-08-28 02:59

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0028_alter_photo_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='instansi',
            name='hitstat',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
