# Generated by Django 3.2.8 on 2024-08-28 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0029_instansi_hitstat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instansi',
            old_name='hitstat',
            new_name='histats',
        ),
    ]
