# Generated by Django 3.2.8 on 2024-08-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0030_rename_hitstat_instansi_histats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instansi',
            name='histats',
            field=models.TextField(blank=True, null=True),
        ),
    ]
