# Generated by Django 4.2.23 on 2025-07-22 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
        ('opd', '0033_rename_judul_seo_berita_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.SmallIntegerField(choices=[(1, 'News'), (2, 'Article'), (3, 'Announcement')], verbose_name='kind')),
                ('is_need_refresh', models.BooleanField(default=False)),
                ('expired', models.DateTimeField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='site')),
            ],
            options={
                'verbose_name': 'log',
                'verbose_name_plural': 'logs',
            },
        ),
        migrations.CreateModel(
            name='AutoLatestNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('sub_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='sub title')),
                ('slug', models.SlugField(blank=True, default='', editable=False, max_length=255)),
                ('photo_path', models.CharField(max_length=1000, verbose_name='photo string')),
                ('kind', models.SmallIntegerField(choices=[(1, 'News'), (2, 'Article'), (3, 'Announcement')], verbose_name='kind')),
                ('is_editable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(editable=False)),
                ('created_at_str', models.CharField(blank=True, max_length=30, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='opd.kategori')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='site')),
            ],
            options={
                'verbose_name': 'auto latest news',
                'verbose_name_plural': 'auto latest news',
            },
        ),
    ]
