# Generated by Django 4.2.23 on 2025-07-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0034_log_autolatestnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autolatestnews',
            name='photo_path',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='photo string'),
        ),
    ]
